### ISSUE TITLE
Knight can't convert Stone Cards, crashing the game

### ISSUE THREAD

**Issue by ChromaPIE** [Aiz0/aiz-balatro-mod#1]
Game crashes when the Knight's trying to convert a Stone Card

EDIT: crash confirmed with some other cards with different types of enhancement. this joker seems pretty unstable.

**Comment by Aiz0** [comment]
Can not reproduce this on dev branch using latest steamodded 1.0.0-ALPHA.
I am having trouble getting steamodded 0.9.8 work again so I can't test it right now.

**Comment by Aiz0** [comment]
This could be a compatibility issue with some other mods. I have not tested for that at all which makes it likely.

**Comment by ChromaPIE** [comment]
sorry and yea i am on 0.9.8. and the enhancements were given by Fabric Design of Pampa Jokers. Playing one single card causes no problem but playing two (like 1 mult card and 1 stone card) crashes the game.

**Comment by ChromaPIE** [comment]
i've moved to 1.0.0 and haven't seen any issue in my few runs with that joker. feel free to just close it.
